Pull req
theheadmen/goDipl3 pull request #1
Opened 2024-05-29 16:18 UTC by theheadmen

2024-05-29 16:20 UTC, theheadmen commented
Работает:
хранение-обновление-удаление,
HTTPS,
шифрование-дешифрование на клиенте,

Не работает:
синхронизация,
локальное сохранение,
сохранение файлов (бинарный тип данных просто хранит данные сейчас)

2024-05-31 06:20 UTC, theheadmen commented
Добавлено:
работа с файлами (сохранение, получение файла по имени, получение списка имен файлов, удаление файла по имени)

2024-06-02 18:42 UTC, bambruysk requested changes
Продолжаем добивать)

2024-06-02 18:42 UTC, bambruysk commented on client/clientapi/clientapi.go
> +	buildDate = time.Now().Format("2006-01-02 15:04:05")
Это работает? линкер подменяет ее? Чисто интересно

2024-06-02 18:42 UTC, bambruysk commented on client/clientapi/clientapi.go
> +		os.Exit(1)
Можно было бы это вынести в какую-то функцию

2024-06-02 18:42 UTC, bambruysk commented on client/clientapi/clientapi.go
> +		}
код много повторяется - стоит вынести его в отдельный слой/пакет

2024-06-02 18:42 UTC, bambruysk commented on server/dbconnector/dbconnector.go
> +		Data:      data["data"].(string),
нужно проверять успешность приведения всегда

2024-06-02 18:42 UTC, bambruysk commented on server/dbconnector/dbconnector.go
> +func StoreTextData(userID int, data map[string]interface{}, db *sql.DB) error {
зачем сюда передавать мапу? может проще было бы сразу структуру?

2024-06-02 18:42 UTC, bambruysk commented on server/serverapi/serverapi.go
> +	var data map[string]interface{}
тут уязвимость - 
я захожу как обычный пользователь 
Отправляю мусорный json - сервер падает потому что паника из-за неудачных приведений интерфейса выше
Лучше преобразовать и валидировать всегда входные данные

2024-06-03 11:43 UTC, theheadmen commented on client/clientapi/clientapi.go
> +		os.Exit(1)
Что именно?
Файл же один раз тут создается

Или os.Exit(1)?

2024-06-04 15:00 UTC, theheadmen commented
Поправлено после комментариев (добавлен пакет utils)
Добавлено шифрование в файлы

Осталось:
видимо самое сложное, локальное хранилище клиента и синхронизация

2024-06-05 15:52 UTC, theheadmen commented
Добавлено UpdatedAT к всем данным

2024-06-06 16:48 UTC, theheadmen commented
Добавлена локальная клиентская бд, но пока только с микротестом на то что в целом идея работает

2024-06-08 11:41 UTC, theheadmen commented
Обновление данных у клиента после вызова "get"

2024-06-09 13:16 UTC, theheadmen commented
Добавлена синхронизация от/на сервер.
Нужно добавить тесты + поправить чехарду с тем в какой момент дешифровать данные на клиенты при синхронизации с локальной бд

2024-06-11 17:44 UTC, bambruysk requested changes
Немного поправить и ок будет

2024-06-11 17:44 UTC, bambruysk commented on client/dbconnector/dbconnector.go
> +		log.Fatalf("Failed to open database: %v", err)
в этой строке уже все зафаталится -  os.Exit не вызовается - лучше написать log.Error()

2024-06-11 17:44 UTC, bambruysk commented on client/dbconnector/dbconnector.go
> +func SaveTextData(db *sql.DB, data models.TextLocalData) error {
не надо таскать через аргументы  соединение - лучше его хранить в структуре -  а это все сделать методами этой структуры. В ней же могут быть логгеры, метрики конфиги итп

2024-06-11 17:44 UTC, bambruysk commented on client/dbconnector/dbconnector.go
> +		`, data.UUID, data.UserID, data.Data, data.Meta, data.UpdatedAt, id)
а в sqlite нет типа UPSERT что-то такого? 
Это все бы в транзакцию завернуть

2024-06-11 17:44 UTC, bambruysk commented on utils/utils.go
> +package utils
Говорят что существоание такого пакета (класса, модуля) - это признак плохой архитектуры

Здесь явно смешано много в кучу - конвертеры можно было бы выделить в отдельные пакеты и положить их в те пакеты где исопльзутся

2024-06-11 17:44 UTC, bambruysk commented on utils/utils.go
> +func CreateBankCard(userID int, data map[string]interface{}) (models.BankCard, error) {
Этот конструктор можно положить в models

2024-06-11 17:44 UTC, bambruysk commented on utils/utils.go
> +func SendRequest(baseURL *url.URL, body io.Reader, reqType string, contentType string, withCookie bool, authCookies []*http.Cookie) (*http.Response, error) {
Это в пакет клиента

2024-06-11 17:44 UTC, bambruysk commented on utils/utils.go
> +	resp, err := client.Do(req)
Лучше использовать goresty

2024-06-11 17:44 UTC, bambruysk commented on utils/utils.go
> +func ConvertTextToLocalData(textData []models.TextData) []models.TextLocalData {
Это в models

2024-06-11 17:44 UTC, bambruysk commented on utils/utils.go
> +func Encrypt(key []byte, text string) (string, error) {
Методы криптования в отдельный пакет crypto

2024-06-12 12:41 UTC, theheadmen commented
Разбил utils на crypt + models
Переделал вызовы функций для БД чтобы они не передавали db *sql.DB
Нашел инструкцию UPDATE OR IGNORE для обновлений
Переделал SaveAndUpdate функции на использовании транзакции

2024-06-21 12:57 UTC, bambruysk approved these changes
принято

2024-06-21 12:57 UTC, bambruysk commented on client/clientapi/clientapi.go
> +	return resp, nil
можно return err

2024-07-08 08:23 UTC, merged